# docker-compose.prod.yml
version: '3.8'

services:
  gamecloud.dashboard:
    container_name: ${DASHBOARD_CONTAINER_NAME}
    image: ${DASHBOARD_IMAGE}:${DASHBOARD_IMAGE_TAG}
    ports:
      - "${DASHBOARD_PORT}:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8081
      - ApiUrl__GameCloud=http://${MAIN_SERVICE_IP}:${MAIN_SERVICE_PORT}
    networks:
      - dashboard_network

networks:
  dashboard_network:
    driver: bridge