apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - dashboard/dashboard-deployment.yaml
  - dashboard/dashboard-service.yaml
  - dashboard/dashboard-ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: gamecloud
    includeSelectors: true
namespace: gamecloud
