name: CI Pipeline

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x'
  YC_REGISTRY: cr.yandex/crpl3p256m938dtgp3lh
  APP_NAME: gamecloud-dashboard

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ env.YC_REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }} -f ./GameCloud.Dashboard/Dockerfile .