name: Build and Deploy to Yandex Cloud
on:
  push:
    branches: [ main ]

env:
  IMAGE_TAG: ${{ github.sha }}
  YC_REGISTRY: cr.yandex/crptfdbrbcnk9hvgef45
  APP_NAME: gamecloud.dashboard

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Yandex Cloud Container Registry
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      
      - name: Build and push
        run: |
          docker build ./GameCloud.Dashboard/Dockerfile -t ${{ env.YC_REGISTRY }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.YC_REGISTRY }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}